# Generated by Django 5.1.4 on 2025-09-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_rolemodel_name_and_more'),
        ('security', '0004_seed_roles'),
    ]

    operations = [
    ]
